# Generated by Django 3.0.4 on 2020-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_office_officer_organization_organizationmember_service_subscriber_subscriptiontype_transferdsubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Allocation',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
